### ISSUE TITLE
About VapourSynth-removedirt,...

### ISSUE THREAD

**Issue by Selur** [Setsugennoao/vs-parsedvd#4]
Sorry, to post here, but https://github.com/Setsugennoao/VapourSynth-removedirt has no issue tracker and I wanted to ask whether you could share a win64bit build of VapourSynth-removedirt.
I'd like to test whether you changes fix an issue I encountered with RestoreMotionBlocks, see: https://forum.doom9.org/showthread.php?p=1964324#post1964324

Thanks :)

**Comment by Setsugennoao** [comment]
Hello, thanks for the interest!
I haven't touched that plugin for 8 months, and i don't remember fixing any issues nor adding features, it was just for building (which I can't find, sorry) since i couldn't compile upstream.
If you provide some use cases and bugs i can do an AVS port of the plugin, since it got updated.
Can you contact me on discord?
Setsugen_no_ao#6969 or preferably in the Irrational Encoding Wizardry [server](https://discord.gg/BN6ZXjVR)

**Comment by kedaitinh12** [comment]
Avs ver of plugin
https://github.com/pinterf/RemoveDirt

**Comment by Selur** [comment]
updates Vapoursynth RemoveDirt would be nice. :)
